# https://taskfile.dev

version: "3"

dotenv:
  - .env

vars:
  BUILD_TYPE: '{{.BUILD_TYPE | default "MinSizeRel"}}'
  BUILD_DIR: "cmake-build-{{.BUILD_TYPE | lower}}"
  PARALLEL_JOBS:
    sh: |
      {{if eq OS "windows"}}
      echo ${NUMBER_OF_PROCESSORS}
      {{else}}
      nproc 2>/dev/null || echo 1
      {{end}}

tasks:
  default:
    summary: Show available tasks
    silent: true
    cmds:
      - task --list

  config:
    desc: Configure the project
    silent: true
    cmds:
      - |
        if [ ! -d "{{.BUILD_DIR}}" ]; then
          mkdir -p {{.BUILD_DIR}}
        fi
        cd {{.BUILD_DIR}}
        cmake .. \
          -DCMAKE_BUILD_TYPE={{.BUILD_TYPE}} \
          {{if .BUILD_SHARED_LIBS}}-DBUILD_SHARED_LIBS={{.BUILD_SHARED_LIBS}}{{end}} \
          {{if .SMF_BUILD_TEST}}-DSMF_BUILD_TEST={{.SMF_BUILD_TEST}}{{end}} \
          {{if .SMF_BUILD_EXAMPLE}}-DSMF_BUILD_EXAMPLE={{.SMF_BUILD_EXAMPLE}}{{end}} \
          {{if .BUILD_ARGS}}{{.BUILD_ARGS}}{{end}}

  build:
    desc: Build the project
    silent: true
    cmds:
      - |
        if [ ! -d "{{.BUILD_DIR}}/CMakeFiles" ]; then
          task config
        fi
        cd {{.BUILD_DIR}}
        cmake --build . --config {{.BUILD_TYPE}} --parallel {{.PARALLEL_JOBS}}

  test:
    desc: Run tests
    silent: true
    deps:
      - task: build
    cmds:
      - |
        cd {{.BUILD_DIR}}
        ctest -C {{.BUILD_TYPE}} --output-on-failure

  clean:
    desc: Clean the build directory
    silent: true
    cmds:
      - rm -rf {{.BUILD_DIR}}
